{% set version = "0.6.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jfa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jfa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jfa/jfa_{{ version }}.tar.gz
  sha256: 6b6d522cc2f927046530113ebee3eeb4174f4754925d820f0a87e7e93ce294dc

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-extradistr
  run:
    - r-base
    - r-extradistr

test:
  commands:
    - $R -e "library('jfa')"           # [not win]
    - "\"%R%\" -e \"library('jfa')\""  # [win]

about:
  home: https://koenderks.github.io/jfa/, https://github.com/koenderks/jfa

  license: GPL-3.0-only
  summary: Implements the audit sampling workflow as discussed in Derks et al. (2019) <doi:10.31234/osf.io/9f6ub>. The package makes it easy for an auditor to plan a statistical sample, select the sample from the population, and evaluate the sample using various methods according to the International Standards on Auditing.
    Furthermore, the package implements Bayesian equivalents of these methods.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
