{% set version = "0.7.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jfa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jfa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jfa/jfa_{{ version }}.tar.gz
  sha256: db6d3ab2cdc9ad1d2a4e3e8a085316f833e8337505b68e3390afc9cf4005b7aa

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bde
    - r-bh >=1.66.0
    - r-extradistr
    - r-ggplot2
    - r-moments
    - r-philentropy
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-rstan >=2.18.1
    - r-rstantools >=2.2.0
    - r-stanheaders >=2.18.0
    - r-truncdist
    - tbb-devel
  run:
    - r-base
    - r-bde
    - r-bh >=1.66.0
    - r-extradistr
    - r-ggplot2
    - r-moments
    - r-philentropy
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-rstan >=2.18.1
    - r-rstantools >=2.2.0
    - r-stanheaders >=2.18.0
    - r-truncdist

test:
  commands:
    - $R -e "library('jfa')"           # [not win]
    - "\"%R%\" -e \"library('jfa')\""  # [win]

about:
  home: https://koenderks.github.io/jfa/
  dev_url: https://github.com/koenderks/jfa
  license: GPL-3.0-only
  summary: Provides statistical methods for auditing as implemented in JASP for Audit (Derks et al., 2021 <doi:10.21105/joss.02733>). First, the package makes it easy for an auditor to plan a statistical sample, select the sample from the population, and evaluate the misstatement in the sample compliant with international
    auditing standards. Next to classical audit sampling methodology, the package implements Bayesian equivalents of these methods whose statistical underpinnings are described in Derks et al. (2021) <doi:10.1111/ijau.12240>, Derks et al. (2021) <doi:10.31234/osf.io/kzqp5>, and Derks et al. (2022) <doi:10.31234/osf.io/8nf3e>.
    Second, the package provides statistical methods for auditing data, including (Bayesian) tests of digit distributions and tests for repeated values.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
